#!/usr/bin/env tsx
/**
 * Indonesian Law MCP — Census-Driven Ingestion Pipeline
 *
 * Fetches Indonesian legislation from two sources:
 *   1. BPK RI (peraturan.bpk.go.id) — full-text HTML with Pasal structure
 *   2. peraturan.go.id (JDIH Nasional) — detail pages for metadata enrichment
 *
 * **Census-driven**: Reads data/census.json (generated by scripts/census.ts) to
 * enumerate ALL Undang-Undang. Falls back to KEY_INDONESIAN_ACTS if census is missing.
 *
 * Pipeline for each law:
 *   1. Try BPK RI Detail page (if bpk_detail_id is known) — full text
 *   2. If BPK unavailable, try to discover BPK detail ID via search
 *   3. Parse HTML → extract Pasal provisions + definitions
 *   4. If no provisions extracted, create metadata-only seed
 *   5. Save structured JSON seed file
 *
 * Usage:
 *   npm run ingest                    # Full ingestion (from census)
 *   npm run ingest -- --limit 5       # Test with 5 laws
 *   npm run ingest -- --skip-fetch    # Reuse cached HTML
 *   npm run ingest -- --resume        # Skip laws that already have seed files
 *
 * Data source: peraturan.bpk.go.id (BPK RI) + peraturan.go.id (JDIH Nasional)
 * License: Government Open Data
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { fetchWithRateLimit } from './lib/fetcher.js';
import {
  parseIndonesianHtml,
  parseBpkHtml,
  KEY_INDONESIAN_ACTS,
  type ActIndexEntry,
  type ParsedAct,
  type CensusLaw,
} from './lib/parser.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const SOURCE_DIR = path.resolve(__dirname, '../data/source');
const SEED_DIR = path.resolve(__dirname, '../data/seed');
const CENSUS_PATH = path.resolve(__dirname, '../data/census.json');

interface CensusData {
  generated_at: string;
  stats: {
    total: number;
    class_ingestable: number;
    class_metadata_only: number;
    class_inaccessible: number;
  };
  ingestion?: {
    completed_at: string;
    total_laws: number;
    total_provisions: number;
    coverage_pct: string;
  };
  laws: CensusLaw[];
}

function parseArgs(): { limit: number | null; skipFetch: boolean; resume: boolean } {
  const args = process.argv.slice(2);
  let limit: number | null = null;
  let skipFetch = false;
  let resume = false;

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--limit' && args[i + 1]) {
      limit = parseInt(args[i + 1], 10);
      i++;
    } else if (args[i] === '--skip-fetch') {
      skipFetch = true;
    } else if (args[i] === '--resume') {
      resume = true;
    }
  }

  return { limit, skipFetch, resume };
}

/**
 * Convert a census law to the legacy ActIndexEntry format for the parser.
 */
function censusLawToActEntry(law: CensusLaw): ActIndexEntry {
  return {
    id: law.id,
    lawType: 'UU',
    lawNumber: law.number,
    lawYear: law.year,
    title: law.title,
    titleEn: law.title_en,
    shortName: `UU ${law.number}/${law.year}`,
    status: (law.status === 'unknown' ? 'in_force' : law.status) as ActIndexEntry['status'],
    issuedDate: '',
    inForceDate: '',
    url: law.url_bpk_ri || law.url_peraturan_go_id,
    description: '',
  };
}

/**
 * Load laws from census.json if available, otherwise fall back to hardcoded list.
 */
function loadLawList(): CensusLaw[] {
  if (fs.existsSync(CENSUS_PATH)) {
    const raw = fs.readFileSync(CENSUS_PATH, 'utf-8');
    const census = JSON.parse(raw) as CensusData;

    console.log(`  Census: ${census.stats.total} laws (generated ${census.generated_at})`);

    // Only include ingestable laws
    const ingestable = census.laws.filter(a => a.classification === 'ingestable');
    console.log(`  Ingestable: ${ingestable.length} laws`);

    return ingestable;
  }

  console.log('  WARNING: No census.json found — falling back to KEY_INDONESIAN_ACTS');
  console.log('  Run: npx tsx scripts/census.ts   to generate full census\n');

  // Convert legacy format
  return KEY_INDONESIAN_ACTS.map(act => ({
    id: act.id,
    slug: `uu-no-${act.lawNumber}-tahun-${act.lawYear}`,
    number: act.lawNumber,
    year: act.lawYear,
    title: act.title,
    title_en: act.titleEn,
    status: act.status as CensusLaw['status'],
    url_peraturan_go_id: '',
    url_bpk_ri: act.url,
    bpk_detail_id: '',
    classification: 'ingestable' as const,
  }));
}

/**
 * Validate that the fetched HTML is actually for the expected law.
 * BPK RI sometimes redirects to unrelated legislation pages.
 */
function validateFetchedContent(html: string, law: CensusLaw): boolean {
  const lowerHtml = html.toLowerCase();

  // Check for law number and year in page
  const numStr = law.number.toLowerCase();
  const yearStr = law.year;

  // Pattern: "nomor X tahun YYYY" or just number + "tahun" + year
  const hasLawRef = lowerHtml.includes(`${numStr}`) && lowerHtml.includes(`tahun ${yearStr}`);

  // Check title tag
  const titleMatch = html.match(/<title[^>]*>([^<]+)<\/title>/i);
  const pageTitle = titleMatch ? titleMatch[1].toLowerCase() : '';
  const titleHasLaw = pageTitle.includes(numStr) && pageTitle.includes(yearStr);

  // Must contain at least one Pasal marker to be useful
  const hasPasal = /Pasal\s+\d/i.test(html);

  return (hasLawRef || titleHasLaw) && hasPasal;
}

/**
 * Generate a metadata-only fallback seed when full text cannot be fetched.
 */
function generateFallbackSeed(law: CensusLaw): ParsedAct {
  const provisions: ParsedAct['provisions'] = [
    {
      provision_ref: 'pasal0',
      chapter: 'Metadata',
      section: '0',
      title: `UU ${law.number}/${law.year} - Summary`,
      content: [
        law.title,
        law.title_en ? `English: ${law.title_en}` : '',
        `Type: UU No. ${law.number} of ${law.year}`,
        `Status: ${law.status}`,
        law.url_peraturan_go_id ? `Source: ${law.url_peraturan_go_id}` : '',
        law.url_bpk_ri ? `BPK RI: ${law.url_bpk_ri}` : '',
        '',
        'Note: Full text could not be fetched. This seed contains metadata only.',
        'Re-run ingestion when source is accessible for full Pasal text.',
      ].filter(Boolean).join('\n'),
    },
  ];

  return {
    id: law.id,
    type: 'statute',
    title: law.title,
    title_en: law.title_en,
    short_name: `UU ${law.number}/${law.year}`,
    status: (law.status === 'unknown' ? 'in_force' : law.status) as ParsedAct['status'],
    issued_date: '',
    in_force_date: '',
    url: law.url_bpk_ri || law.url_peraturan_go_id,
    description: '',
    provisions,
    definitions: [],
  };
}

/**
 * Attempt to fetch full text from BPK RI for a given law.
 */
async function fetchFromBpkRi(law: CensusLaw): Promise<{ html: string; source: string } | null> {
  // If we have a known BPK Detail ID, use it
  if (law.bpk_detail_id) {
    const url = `https://peraturan.bpk.go.id/Details/${law.bpk_detail_id}/${law.slug}`;
    try {
      const result = await fetchWithRateLimit(url);
      if (result.status === 200 && result.body.length > 1000) {
        return { html: result.body, source: 'bpk-detail' };
      }
    } catch {
      // Fall through to next method
    }
  }

  // Try common BPK URL pattern
  const url = `https://peraturan.bpk.go.id/Search?filter=${encodeURIComponent(`uu no ${law.number} tahun ${law.year}`)}&jenis=9`;
  try {
    const result = await fetchWithRateLimit(url);
    if (result.status === 200) {
      // Try to extract detail link from search results
      const detailMatch = result.body.match(
        new RegExp(`/Details/(\\d+)/uu-no-${law.number}-tahun-${law.year}`, 'i')
      );
      if (detailMatch) {
        const detailId = detailMatch[1];
        const detailUrl = `https://peraturan.bpk.go.id/Details/${detailId}/${law.slug}`;
        const detailResult = await fetchWithRateLimit(detailUrl);
        if (detailResult.status === 200 && detailResult.body.length > 1000) {
          // Save discovered BPK ID for future use
          law.bpk_detail_id = detailId;
          return { html: detailResult.body, source: 'bpk-search' };
        }
      }
    }
  } catch {
    // BPK RI is likely geo-blocked
  }

  return null;
}

async function fetchAndParseLaws(
  laws: CensusLaw[],
  skipFetch: boolean,
  resume: boolean,
): Promise<void> {
  console.log(`\nProcessing ${laws.length} Undang-Undang...\n`);

  fs.mkdirSync(SOURCE_DIR, { recursive: true });
  fs.mkdirSync(SEED_DIR, { recursive: true });

  let processed = 0;
  let resumed = 0;
  let cached = 0;
  let fetched = 0;
  let fallbacks = 0;
  let failed = 0;
  let totalProvisions = 0;
  let totalDefinitions = 0;
  const startTime = Date.now();

  const report: { law: string; provisions: number; definitions: number; status: string }[] = [];

  for (const law of laws) {
    const sourceFile = path.join(SOURCE_DIR, `${law.id}.html`);
    const seedFile = path.join(SEED_DIR, `${law.id}.json`);

    // Resume support: skip laws that already have seed files
    if (resume && fs.existsSync(seedFile)) {
      try {
        const existing = JSON.parse(fs.readFileSync(seedFile, 'utf-8')) as ParsedAct;
        totalProvisions += existing.provisions.length;
        totalDefinitions += existing.definitions.length;
      } catch {
        // Corrupted seed file, re-process
      }
      resumed++;
      processed++;
      continue;
    }

    // Skip if seed already exists and we're in skip-fetch mode
    if (skipFetch && fs.existsSync(seedFile)) {
      try {
        const existing = JSON.parse(fs.readFileSync(seedFile, 'utf-8')) as ParsedAct;
        totalProvisions += existing.provisions.length;
        totalDefinitions += existing.definitions.length;
        report.push({
          law: `UU ${law.number}/${law.year}`,
          provisions: existing.provisions.length,
          definitions: existing.definitions.length,
          status: 'cached',
        });
      } catch {
        // Corrupted, skip
      }
      cached++;
      processed++;
      continue;
    }

    const shortName = `UU ${law.number}/${law.year}`;

    try {
      let html: string | null = null;
      let source = '';

      // Check for cached source HTML
      if (fs.existsSync(sourceFile) && skipFetch) {
        html = fs.readFileSync(sourceFile, 'utf-8');
        source = 'cached-html';
        console.log(`  [${processed + 1}/${laws.length}] Using cached ${shortName}`);
      } else if (fs.existsSync(sourceFile) && !skipFetch) {
        // We have cached HTML from a previous fetch
        html = fs.readFileSync(sourceFile, 'utf-8');
        source = 'cached-html';
        console.log(`  [${processed + 1}/${laws.length}] Using cached ${shortName}`);
      } else if (!skipFetch && law.bpk_detail_id) {
        // Only try network fetch if we have a BPK Detail ID
        process.stdout.write(`  [${processed + 1}/${laws.length}] Fetching ${shortName}...`);

        const bpkResult = await fetchFromBpkRi(law);
        if (bpkResult) {
          html = bpkResult.html;
          source = bpkResult.source;

          if (!validateFetchedContent(html, law)) {
            console.log(` BPK content mismatch`);
            html = null;
          } else {
            console.log(` OK via ${source} (${(html.length / 1024).toFixed(0)} KB)`);
          }
        }

        if (!html) {
          console.log(` unavailable`);
        }
      } else if (!skipFetch) {
        // No BPK ID and no cached HTML — skip network, go straight to fallback
        // (peraturan.go.id detail pages don't contain inline article text)
      }

      // Parse the HTML if we have it
      if (html && source) {
        // Cache the HTML source
        if (source !== 'cached-html') {
          fs.writeFileSync(sourceFile, html);
        }

        const parsed = parseBpkHtml(html, law);

        if (parsed.provisions.length > 0) {
          fs.writeFileSync(seedFile, JSON.stringify(parsed, null, 2));
          totalProvisions += parsed.provisions.length;
          totalDefinitions += parsed.definitions.length;
          report.push({
            law: shortName,
            provisions: parsed.provisions.length,
            definitions: parsed.definitions.length,
            status: `OK (${source})`,
          });
          fetched++;
          console.log(`    -> ${parsed.provisions.length} provisions, ${parsed.definitions.length} definitions`);
        } else {
          // HTML found but no provisions parsed — fallback
          const fallbackSeed = generateFallbackSeed(law);
          fs.writeFileSync(seedFile, JSON.stringify(fallbackSeed, null, 2));
          totalProvisions += fallbackSeed.provisions.length;
          report.push({
            law: shortName,
            provisions: fallbackSeed.provisions.length,
            definitions: 0,
            status: `fallback (no provisions)`,
          });
          fallbacks++;
        }
      } else {
        // No HTML available — generate fallback seed
        const fallbackSeed = generateFallbackSeed(law);
        fs.writeFileSync(seedFile, JSON.stringify(fallbackSeed, null, 2));
        totalProvisions += fallbackSeed.provisions.length;
        report.push({
          law: shortName,
          provisions: fallbackSeed.provisions.length,
          definitions: 0,
          status: 'fallback (no source)',
        });
        fallbacks++;
      }
    } catch (error) {
      const msg = error instanceof Error ? error.message : String(error);
      console.log(`  ERROR ${shortName}: ${msg}`);

      // Generate fallback on error
      const fallbackSeed = generateFallbackSeed(law);
      fs.writeFileSync(seedFile, JSON.stringify(fallbackSeed, null, 2));
      totalProvisions += fallbackSeed.provisions.length;
      report.push({
        law: shortName,
        provisions: fallbackSeed.provisions.length,
        definitions: 0,
        status: `fallback (${msg.substring(0, 50)})`,
      });
      fallbacks++;
      failed++;
    }

    processed++;

    // Progress every 25 laws
    if (processed % 25 === 0) {
      const elapsed = ((Date.now() - startTime) / 1000).toFixed(0);
      const eta = processed > 0
        ? ((Date.now() - startTime) / processed * (laws.length - processed) / 1000).toFixed(0)
        : '?';
      console.log(`\n  --- Progress: ${processed}/${laws.length} (${elapsed}s elapsed, ~${eta}s remaining) ---\n`);
    }
  }

  const totalElapsed = ((Date.now() - startTime) / 1000).toFixed(1);

  // Print summary report
  console.log(`\n${'='.repeat(75)}`);
  console.log('INGESTION REPORT');
  console.log('='.repeat(75));
  console.log(`\n  Source:      peraturan.bpk.go.id + peraturan.go.id`);

  if (report.length <= 80) {
    console.log(`\n  ${'Law'.padEnd(20)} ${'Provisions'.padStart(12)} ${'Definitions'.padStart(13)}  Status`);
    console.log(`  ${'-'.repeat(20)} ${'-'.repeat(12)} ${'-'.repeat(13)}  ${'-'.repeat(30)}`);
    for (const r of report) {
      console.log(
        `  ${r.law.padEnd(20)} ${String(r.provisions).padStart(12)} ${String(r.definitions).padStart(13)}  ${r.status}`,
      );
    }
  } else {
    const okCount = report.filter(r => r.status.startsWith('OK')).length;
    const fallbackCount = report.filter(r => r.status.startsWith('fallback')).length;
    const cachedCount = report.filter(r => r.status === 'cached').length;
    console.log(`\n  New ingestions (full text): ${okCount}`);
    console.log(`  Fallback (metadata only):  ${fallbackCount}`);
    console.log(`  Cached:                    ${cachedCount}`);

    if (okCount > 0 && okCount <= 50) {
      console.log('\n  Successfully ingested:');
      for (const r of report.filter(r => r.status.startsWith('OK'))) {
        console.log(`    ${r.law.padEnd(20)} ${r.provisions} provisions  ${r.status}`);
      }
    }
  }

  console.log(`\n${'='.repeat(75)}`);
  console.log(`  Total elapsed:     ${totalElapsed}s`);
  console.log(`  Processed:         ${processed}`);
  console.log(`  Resumed:           ${resumed}`);
  console.log(`  Cached:            ${cached}`);
  console.log(`  Fetched (full):    ${fetched}`);
  console.log(`  Fallbacks:         ${fallbacks}`);
  console.log(`  Failed:            ${failed}`);
  console.log(`  Total provisions:  ${totalProvisions}`);
  console.log(`  Total definitions: ${totalDefinitions}`);

  // Update census.json with ingestion stats
  if (fs.existsSync(CENSUS_PATH)) {
    const census = JSON.parse(fs.readFileSync(CENSUS_PATH, 'utf-8'));
    census.ingestion = {
      completed_at: new Date().toISOString(),
      total_laws: processed - failed,
      total_provisions: totalProvisions,
      coverage_pct: ((processed - failed) / laws.length * 100).toFixed(1),
    };
    fs.writeFileSync(CENSUS_PATH, JSON.stringify(census, null, 2) + '\n');
    console.log(`\n  Updated census.json with ingestion stats.`);
  }

  if (fallbacks > 0) {
    console.log(`\n  NOTE: ${fallbacks} law(s) used fallback seeds (metadata only).`);
    console.log('  Re-run ingestion from an Indonesian IP for full BPK RI text.\n');
  }
}

async function main(): Promise<void> {
  const { limit, skipFetch, resume } = parseArgs();

  console.log('Indonesian Law MCP — Ingestion Pipeline');
  console.log('=======================================\n');
  console.log(`  Source: peraturan.bpk.go.id (BPK RI) + peraturan.go.id (JDIH)`);
  console.log(`  Format: HTML with Pasal/Bab structure`);
  console.log(`  License: Government Open Data`);
  console.log(`  Rate limit: 500ms between requests, max 3 concurrent`);

  if (limit) console.log(`  --limit ${limit}`);
  if (skipFetch) console.log(`  --skip-fetch`);
  if (resume) console.log(`  --resume (skip existing seed files)`);

  const allLaws = loadLawList();
  const laws = limit ? allLaws.slice(0, limit) : allLaws;
  await fetchAndParseLaws(laws, skipFetch, resume);
}

main().catch(error => {
  console.error('Fatal error:', error);
  process.exit(1);
});
